; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.60315.1 

	TITLE	C:\Users\remizovm\Documents\GitHub\KengTrainerEngine\keng-hook\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?g_D3D9_Present@@3P6GJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@ZA ; g_D3D9_Present
PUBLIC	?g_D3D9_DIP@@3P6GJPAUIDirect3DDevice9@@W4_D3DPRIMITIVETYPE@@HIIII@ZA ; g_D3D9_DIP
PUBLIC	?g_codeFragment_p9@@3PAEA			; g_codeFragment_p9
PUBLIC	?g_jmp_p9@@3PAEA				; g_jmp_p9
PUBLIC	?g_savedProtection_p9@@3KA			; g_savedProtection_p9
PUBLIC	?present9@@3KA					; present9
PUBLIC	?indicator@@3HA					; indicator
PUBLIC	?rec@@3U_D3DRECT@@A				; rec
_BSS	SEGMENT
?g_D3D9_Present@@3P6GJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@ZA DD 01H DUP (?) ; g_D3D9_Present
?g_D3D9_DIP@@3P6GJPAUIDirect3DDevice9@@W4_D3DPRIMITIVETYPE@@HIIII@ZA DD 01H DUP (?) ; g_D3D9_DIP
?g_codeFragment_p9@@3PAEA DB 05H DUP (?)		; g_codeFragment_p9
	ALIGN	4

?g_jmp_p9@@3PAEA DB 05H DUP (?)				; g_jmp_p9
	ALIGN	4

?g_savedProtection_p9@@3KA DD 01H DUP (?)		; g_savedProtection_p9
?present9@@3KA DD 01H DUP (?)				; present9
?indicator@@3HA DD 01H DUP (?)				; indicator
_BSS	ENDS
_DATA	SEGMENT
?rec@@3U_D3DRECT@@A DD 0aH				; rec
	DD	0aH
	DD	0a0H
	DD	0f0H
_DATA	ENDS
PUBLIC	?DrawIndicator@@YAXPAX@Z			; DrawIndicator
PUBLIC	?GetDevice9Methods@@YAXXZ			; GetDevice9Methods
PUBLIC	?HookedPresent9@@YGJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@Z ; HookedPresent9
PUBLIC	?HookDevice9Methods@@YAXXZ			; HookDevice9Methods
PUBLIC	?TF@@YAXXZ					; TF
PUBLIC	?KeyboardHook@@YAXXZ				; KeyboardHook
PUBLIC	_DllMain@12
PUBLIC	??_C@_05JLNEMJLN@dummy?$AA@			; `string'
PUBLIC	??_C@_06GCFCNKMP@STATIC?$AA@			; `string'
PUBLIC	??_C@_04PGKLGAGG@d3d9?$AA@			; `string'
PUBLIC	??_C@_0BA@FAFMMBOF@Direct3DCreate9?$AA@		; `string'
PUBLIC	??_C@_08NIHLGCK@d3d9?4dll?$AA@			; `string'
EXTRN	__imp__Beep@8:PROC
EXTRN	__imp__CloseHandle@4:PROC
EXTRN	__imp__Sleep@4:PROC
EXTRN	__imp__CreateThread@24:PROC
EXTRN	__imp__VirtualProtect@16:PROC
EXTRN	__imp__FreeLibrary@4:PROC
EXTRN	__imp__GetModuleHandleA@4:PROC
EXTRN	__imp__GetProcAddress@8:PROC
EXTRN	__imp__LoadLibraryA@4:PROC
EXTRN	__imp__CreateWindowExA@48:PROC
EXTRN	__imp__GetAsyncKeyState@4:PROC
EXTRN	_memset:PROC
;	COMDAT ??_C@_08NIHLGCK@d3d9?4dll?$AA@
CONST	SEGMENT
??_C@_08NIHLGCK@d3d9?4dll?$AA@ DB 'd3d9.dll', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@FAFMMBOF@Direct3DCreate9?$AA@
CONST	SEGMENT
??_C@_0BA@FAFMMBOF@Direct3DCreate9?$AA@ DB 'Direct3DCreate9', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_04PGKLGAGG@d3d9?$AA@
CONST	SEGMENT
??_C@_04PGKLGAGG@d3d9?$AA@ DB 'd3d9', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_06GCFCNKMP@STATIC?$AA@
CONST	SEGMENT
??_C@_06GCFCNKMP@STATIC?$AA@ DB 'STATIC', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_05JLNEMJLN@dummy?$AA@
CONST	SEGMENT
??_C@_05JLNEMJLN@dummy?$AA@ DB 'dummy', 00H		; `string'
CONST	ENDS
; Function compile flags: /Ogtp
;	COMDAT _DllMain@12
_TEXT	SEGMENT
_hInst$ = 8						; size = 4
_ul_reason_for_call$ = 12				; size = 4
_lpReserved$ = 16					; size = 4
_DllMain@12 PROC					; COMDAT
; File c:\users\remizovm\documents\github\kengtrainerengine\keng-hook\main.cpp
; Line 152
	push	ebp
	mov	ebp, esp
; Line 153
	dec	DWORD PTR _ul_reason_for_call$[ebp]
	jne	SHORT $LN6@DllMain
; Line 156
	push	200					; 000000c8H
	push	500					; 000001f4H
	call	DWORD PTR __imp__Beep@8
; Line 157
	push	0
	push	0
	push	0
	push	OFFSET ?TF@@YAXXZ			; TF
	push	0
	push	0
	call	DWORD PTR __imp__CreateThread@24
; Line 158
	push	0
	push	0
	push	0
	push	OFFSET ?KeyboardHook@@YAXXZ		; KeyboardHook
	push	0
	push	0
	call	DWORD PTR __imp__CreateThread@24
$LN6@DllMain:
; Line 160
	mov	eax, 1
; Line 161
	pop	ebp
	ret	12					; 0000000cH
_DllMain@12 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?KeyboardHook@@YAXXZ
_TEXT	SEGMENT
?KeyboardHook@@YAXXZ PROC				; KeyboardHook, COMDAT
; File c:\users\remizovm\documents\github\kengtrainerengine\keng-hook\main.cpp
; Line 138
	push	ebx
	mov	ebx, DWORD PTR __imp__Beep@8
	push	esi
	mov	esi, DWORD PTR __imp__Sleep@4
	push	edi
	mov	edi, DWORD PTR __imp__GetAsyncKeyState@4
$LL3@KeyboardHo:
; Line 141
	push	112					; 00000070H
	call	edi
	test	ax, ax
	je	SHORT $LN1@KeyboardHo
; Line 143
	xor	eax, eax
	cmp	DWORD PTR ?indicator@@3HA, eax		; indicator
; Line 144
	push	200					; 000000c8H
	sete	al
	push	500					; 000001f4H
	mov	DWORD PTR ?indicator@@3HA, eax		; indicator
	call	ebx
$LN1@KeyboardHo:
; Line 146
	push	100					; 00000064H
	call	esi
; Line 147
	jmp	SHORT $LL3@KeyboardHo
?KeyboardHook@@YAXXZ ENDP				; KeyboardHook
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?TF@@YAXXZ
_TEXT	SEGMENT
?TF@@YAXXZ PROC						; TF, COMDAT
; File c:\users\remizovm\documents\github\kengtrainerengine\keng-hook\main.cpp
; Line 132
	call	?GetDevice9Methods@@YAXXZ		; GetDevice9Methods
; Line 133
	jmp	?HookDevice9Methods@@YAXXZ		; HookDevice9Methods
?TF@@YAXXZ ENDP						; TF
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?HookDevice9Methods@@YAXXZ
_TEXT	SEGMENT
?HookDevice9Methods@@YAXXZ PROC				; HookDevice9Methods, COMDAT
; File c:\users\remizovm\documents\github\kengtrainerengine\keng-hook\main.cpp
; Line 111
	push	OFFSET ??_C@_08NIHLGCK@d3d9?4dll?$AA@
	call	DWORD PTR __imp__GetModuleHandleA@4
; Line 112
	mov	ecx, DWORD PTR ?present9@@3KA		; present9
	add	ecx, eax
; Line 115
	mov	eax, OFFSET ?HookedPresent9@@YGJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@Z ; HookedPresent9
	sub	eax, ecx
	sub	eax, 5
; Line 117
	push	OFFSET ?g_savedProtection_p9@@3KA	; g_savedProtection_p9
	mov	DWORD PTR ?g_D3D9_Present@@3P6GJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@ZA, ecx ; g_D3D9_Present
	mov	BYTE PTR ?g_jmp_p9@@3PAEA, 233		; 000000e9H
	mov	DWORD PTR ?g_jmp_p9@@3PAEA+1, eax
	mov	eax, DWORD PTR [ecx]
	push	64					; 00000040H
	mov	DWORD PTR ?g_codeFragment_p9@@3PAEA, eax
	mov	al, BYTE PTR [ecx+4]
	push	8
	push	ecx
	mov	BYTE PTR ?g_codeFragment_p9@@3PAEA+4, al
	call	DWORD PTR __imp__VirtualProtect@16
; Line 118
	mov	eax, DWORD PTR ?g_D3D9_Present@@3P6GJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@ZA ; g_D3D9_Present
	mov	ecx, DWORD PTR ?g_jmp_p9@@3PAEA
	mov	DWORD PTR [eax], ecx
	mov	eax, DWORD PTR ?g_D3D9_Present@@3P6GJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@ZA ; g_D3D9_Present
	mov	cl, BYTE PTR ?g_jmp_p9@@3PAEA+4
	mov	BYTE PTR [eax+4], cl
; Line 127
	ret	0
?HookDevice9Methods@@YAXXZ ENDP				; HookDevice9Methods
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?HookedPresent9@@YGJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@Z
_TEXT	SEGMENT
_g_pSurface$ = -4					; size = 4
_pDevice$ = 8						; size = 4
_src$ = 12						; size = 4
_dest$ = 16						; size = 4
_hWnd$ = 20						; size = 4
_unused$ = 24						; size = 4
?HookedPresent9@@YGJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@Z PROC ; HookedPresent9, COMDAT
; File c:\users\remizovm\documents\github\kengtrainerengine\keng-hook\main.cpp
; Line 77
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 81
	mov	al, BYTE PTR ?g_codeFragment_p9@@3PAEA
	push	esi
; Line 84
	mov	esi, DWORD PTR _pDevice$[ebp]
	push	edi
	mov	edi, DWORD PTR ?g_D3D9_Present@@3P6GJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@ZA ; g_D3D9_Present
	lea	ecx, DWORD PTR _g_pSurface$[ebp]
	push	ecx
	push	0
	mov	BYTE PTR [edi], al
	mov	eax, DWORD PTR ?g_codeFragment_p9@@3PAEA+1
	push	0
	mov	DWORD PTR [edi+1], eax
	mov	eax, DWORD PTR [esi]
	push	0
	push	esi
	call	DWORD PTR [eax+72]
; Line 89
	push	DWORD PTR _unused$[ebp]
	push	DWORD PTR _hWnd$[ebp]
	push	DWORD PTR _dest$[ebp]
	push	DWORD PTR _src$[ebp]
	push	esi
	call	DWORD PTR ?g_D3D9_Present@@3P6GJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@ZA ; g_D3D9_Present
; Line 90
	mov	cl, BYTE PTR ?g_jmp_p9@@3PAEA
	mov	BYTE PTR [edi], cl
; Line 91
	mov	ecx, DWORD PTR ?g_jmp_p9@@3PAEA+1
	mov	DWORD PTR [edi+1], ecx
	pop	edi
	pop	esi
; Line 93
	mov	esp, ebp
	pop	ebp
	ret	20					; 00000014H
?HookedPresent9@@YGJPAUIDirect3DDevice9@@PBUtagRECT@@1PAUHWND__@@PAX@Z ENDP ; HookedPresent9
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?GetDevice9Methods@@YAXXZ
_TEXT	SEGMENT
_d3dpp$ = -60						; size = 56
_d3dDevice$ = -4					; size = 4
?GetDevice9Methods@@YAXXZ PROC				; GetDevice9Methods, COMDAT
; File c:\users\remizovm\documents\github\kengtrainerengine\keng-hook\main.cpp
; Line 51
	push	ebp
	mov	ebp, esp
	sub	esp, 60					; 0000003cH
	push	ebx
	push	esi
	push	edi
; Line 54
	push	0
	push	0
	push	0
	push	0
	push	0
	push	0
	push	0
	push	0
	push	0
	push	OFFSET ??_C@_05JLNEMJLN@dummy?$AA@
	push	OFFSET ??_C@_06GCFCNKMP@STATIC?$AA@
	push	0
	call	DWORD PTR __imp__CreateWindowExA@48
; Line 55
	push	OFFSET ??_C@_04PGKLGAGG@d3d9?$AA@
	mov	ebx, eax
	call	DWORD PTR __imp__LoadLibraryA@4
	mov	edi, eax
; Line 56
	push	OFFSET ??_C@_0BA@FAFMMBOF@Direct3DCreate9?$AA@
	push	edi
	call	DWORD PTR __imp__GetProcAddress@8
; Line 57
	push	32					; 00000020H
	call	eax
; Line 59
	push	56					; 00000038H
	mov	esi, eax
	lea	eax, DWORD PTR _d3dpp$[ebp]
	push	0
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
; Line 62
	lea	eax, DWORD PTR _d3dDevice$[ebp]
	push	eax
	lea	eax, DWORD PTR _d3dpp$[ebp]
	push	eax
	push	32					; 00000020H
	push	ebx
	push	1
	mov	DWORD PTR _d3dpp$[ebp+32], 1
	mov	DWORD PTR _d3dpp$[ebp+24], 1
	mov	ecx, DWORD PTR [esi]
	push	0
	push	esi
	call	DWORD PTR [ecx+64]
; Line 65
	mov	ecx, DWORD PTR _d3dDevice$[ebp]
; Line 67
	push	ecx
	mov	eax, DWORD PTR [ecx]
	mov	eax, DWORD PTR [eax+68]
	sub	eax, edi
	mov	DWORD PTR ?present9@@3KA, eax		; present9
	mov	eax, DWORD PTR [ecx]
	call	DWORD PTR [eax+8]
; Line 69
	mov	eax, DWORD PTR [esi]
	push	esi
	call	DWORD PTR [eax+8]
; Line 71
	push	edi
	call	DWORD PTR __imp__FreeLibrary@4
; Line 72
	push	ebx
	call	DWORD PTR __imp__CloseHandle@4
	pop	edi
	pop	esi
	pop	ebx
; Line 73
	mov	esp, ebp
	pop	ebp
	ret	0
?GetDevice9Methods@@YAXXZ ENDP				; GetDevice9Methods
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?DrawIndicator@@YAXPAX@Z
_TEXT	SEGMENT
_self$ = 8						; size = 4
?DrawIndicator@@YAXPAX@Z PROC				; DrawIndicator, COMDAT
; File c:\users\remizovm\documents\github\kengtrainerengine\keng-hook\main.cpp
; Line 22
	push	ebp
	mov	ebp, esp
	push	esi
; Line 34
	mov	esi, DWORD PTR _self$[ebp]
	push	esi
	mov	eax, DWORD PTR [esi]
	call	DWORD PTR [eax+164]
; Line 45
	mov	eax, DWORD PTR [esi]
	push	esi
	call	DWORD PTR [eax+168]
	pop	esi
; Line 47
	pop	ebp
	ret	0
?DrawIndicator@@YAXPAX@Z ENDP				; DrawIndicator
_TEXT	ENDS
END
